---
- name: Installer et configurer Apache2
  hosts: all
  become: yes

  tasks:
    - name: Installer Apache2
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Démarrer et activer Apache2
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

    - name: Créer un répertoire pour le site web
      ansible.builtin.file:
        path: /var/www/html
        state: directory

    - name: Copier un fichier HTML de base
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
          <html>
            <head>
              <title>Bienvenue sur Apache2 de Gissou</title>
            </head>
            <body>
              <h1>Félicitations Gissou ! Apache2 est installé et fonctionne.</h1>
            </body>
          </html>
