all:
  hosts:
    10.10.10.113:
      ansible_user: root
    10.10.10.114:
      ansible_user: root
    10.10.10.115:
      ansible_user: root
  children:
    webservers:
      hosts:
        10.10.10.113:
        10.10.10.114:
          
