---
- name: Installer et configurer mysql
  hosts: dbservers
  become: yes
  
  vars_files:
    - vars/main.yml
    - vars/db.yml
    
  tasks:        
    - name: Installer mysql via un role
      ansible.builtin.include_role:
        name: geerlingguy.mysql
